spring:
  application:
    name: taco_cloud_client
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - writeIngredients
              - deleteIngredients
              - writeOrders
              - deleteOrders
              - openid

        provider:
          tacocloud:
              authorization-uri: ${AUTH_AUTHORIZATION_URI:http://localhost:9000/oauth2/authorize}
              token-uri: ${AUTH_TOKEN_URI:http://localhost:9000/oauth2/token}
              jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:9000/oauth2/jwks}

api:
  base-url: ${API_BASE_URL:http://localhost:8080}

server:
  port: ${SERVER_PORT:9090}
  servlet:
    session:
      cookie:
        name: CLIENTSESSION