spring:
  application:
    name: shaverma-cloud
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:shavermadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  # В Spring Boot 3.x консоль H2 включена ПО УМОЛЧАНИЮ
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

  # SQL init (опционально)
  sql:
    init:
      mode: always

  security:
    oauth2:
     resourceserver:
       jwt:
         jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:9000/oauth2/jwks}

# Server
server:
  port: 8080